version: "3.8"
name: 'bookstore-spring-boot-microservices'
services:
  catalog-db:
    image: mysql:8.0.38          # Specify the MySQL image and version
    container_name: catalog-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://catalog-db:3306/testdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "3306:3306"                      # Map MySQL port
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
